### PR TITLE
bringing fork up to date

### PR DESCRIPTION
**Pull request by szlin**

### CODE REVIEW

**Comment by szlin** [comment]
The description in libhyperscan4.2-dev and libhyperscan4.2 cannot be the same due to policy of lintian,
so I write a draft description for libhyperscan4.2-dev.

**Comment by hillu** [comment]
I am not sure whether changing the -dev package name is really necessary. (Changing the description is ok, though.). If you chagnge the package name, however, you'll need to rename the .install file.

**Comment by szlin** [comment]
I suggest that we can refer to libpcap [1].  The libpcap-dev offers empty package to facilitate upgrades, can be safely removed, and it depends on libpcap0.8-dev.

Whatever the outcome might be, I totally respect your decision :)

The change of description is *necessary*; otherwise, it fails when running lintian.

[1] https://packages.debian.org/jessie-backports/libpcap-dev
[2] https://packages.debian.org/source/jessie-backports/libpcap

**Comment by hillu** [comment]
I just pushed the description change, but after looking for other examples to follow, it occurred to me that the majority of lib* packages that have (part of) aversion number in their name com with a -dev package that does not contain the version number. libpcap is an outlier rather than the norm.

**Comment by szlin** [comment]
According to https://debian-handbook.info/browse/stable/sect.package-meta-information.html

> The dependencies system is a good mechanism for guaranteeing the operation of a program, but it has another use with “meta-packages”. These are empty packages that only describe dependencies. They facilitate the installation of a consistent group of programs preselected by the meta-package maintainer; as such, apt install meta-package will automatically install all of these programs using the meta-package's dependencies. The gnome, kde-full and linux-image-amd64 packages are examples of meta-packages. 

I think libpcap is not an outlier but just another packing solution which runs above mechanism.

one way or another is OK for me :)

**Comment by SleuthKid** [comment]
With reference to https://www.debian.org/doc/debian-policy/ch-sharedlibs.html#s-sharedlibs-dev @szlin seems right about the naming.

@szlin could you undo the changes to the changelog and keep the naming and description change of the control file? Then I will merge this PR.

**Comment by szlin** [comment]
@SleuthKid  I reverted the commit.

**Comment by SleuthKid** [comment]
Oh sorry. I have seen this to late. My bad.

I have updated the debian/control file with a description stating the importance of SSSE3 with the processor and included your suggestions. Is this okay with you?
See https://github.com/SleuthKid/hyperscan/commit/a2b14b9c23df891537beb404170f76c877e53583

**Comment by szlin** [comment]
Sure, I think it's cool.
I am going to solve some warnings/ errors  after running lintian in these days.

**Pull request closed without merging**
